[package]
name = "anyrag-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
# Internal Crate
anyrag = { path = "../lib" }

# Web Framework
axum = { workspace = true }
axum-extra = { version = "0.10.1", features = ["multipart"] }

# Async runtime
tokio = { workspace = true }

# Tracing & Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tower-http = { workspace = true }

# Serde
serde = { workspace = true }
serde_json.workspace = true
turso = { workspace = true }
futures = { workspace = true }

# Other
dotenvy = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
dyn-clone = { workspace = true }
futures = "0.3.31"
gcp-bigquery-client = { workspace = true }
reqwest = { workspace = true, features = ["json", "multipart"] }
httpmock = "0.7.0"
tempfile = "3.20.0"
turso = { workspace = true }
regex = { workspace = true }
md5 = "0.7.0"
genpdf = "0.2.0"
rusttype = "0.9.3"

[[test]]
name = "config_test"
path = "tests/config_test.rs"
harness = true

[[test]]
name = "server_test"
path = "tests/server_test.rs"
harness = true

[[test]]
name = "content_type_test"
path = "tests/content_type_test.rs"
harness = true

[[test]]
name = "ingest_test"
path = "tests/ingest_test.rs"
harness = true

[[test]]
name = "embedding_test"
path = "tests/embedding_test.rs"
harness = true

[[test]]
name = "ingest_text_test"
path = "tests/ingest_text_test.rs"
harness = true

[[test]]
name = "pdf_ingest_test"
path = "tests/pdf_ingest_test.rs"
harness = true
