[package]
name = "anyrag-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
# Internal Crate
anyrag = { path = "../lib" }

# Web Framework
axum = { workspace = true }

# Async runtime
tokio = { workspace = true }

# Tracing & Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tower-http = { workspace = true }

# Serde
serde = { workspace = true }
serde_json.workspace = true
turso = { workspace = true }

# Other
dotenvy = "0.15.7"
anyhow = "1.0.98"

[dev-dependencies]
async-trait = { workspace = true }
dyn-clone = { workspace = true }
gcp-bigquery-client = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
httpmock = "0.7.0"
tempfile = "3.10.1"
turso = "0.1.3"

[[test]]
name = "config_test"
path = "tests/config_test.rs"
harness = true

[[test]]
name = "server_test"
path = "tests/server_test.rs"
harness = true

[[test]]
name = "ingest_test"
path = "tests/ingest_test.rs"
harness = true

[[test]]
name = "embedding_test"
path = "tests/embedding_test.rs"
harness = true
